"""Multi-turn planning with phrasing variants and verbal cues, on the "Continue" protocol of multiturn_planning/
(same system rules, scenarios, step format, prefill, cutting and capture positions; imported from ../multiturn_planning).

Conditions (one ConvSpec each):
  base      canonical horizon sentence, greedy                 scenario x horizon
  unit      the horizon in another unit/form, greedy           scenario x horizon x form (where defined)
  implicit  implicit horizon / its explicit twin, greedy       personal scenario x implicit item x {implicit, twin}
  free      no horizon at all (the model picks), sampled       scenario x sample
Cues: `first`  = cue appended to the first user turn (a new conversation);
      `step`   = cue appended to the "Continue" that asks for step `cue_step`. These conversations BRANCH from their
                 no-cue parent: turns before the cue are copied from the parent (identical by construction), so the
                 cue's effect on later steps is a paired comparison with the parent.
"""

from __future__ import annotations

import itertools
import json
import math
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from safetensors.torch import save_file

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "multiturn_planning"))
from mtp.chat import POSITIONS, clean_reply, cut_step_reply, encode_prompt, turn_positions  # noqa: E402
from mtp.prompts import (CONTINUE, N_STEPS, SCENARIOS, SYSTEM, outline_mentions_time,  # noqa: E402
                         parse_step, step_prefill)
from mtp.run import MAX_NEW, N_TURNS, SAMPLING, Capture, generate_batch, turn_kind  # noqa: E402

from .durations import parse_years  # noqa: E402


@dataclass(frozen=True)
class ConvSpec:
    conv_id: str
    scenario: str
    condition: str            # base | unit | implicit | twin | free
    variant: str              # canonical | <form> | implicit:<id> | twin:<id> | none
    level: str | None         # canonical horizon level, implicit id, or None
    h_text: str | None
    h_years: float
    cue: str | None
    cue_where: str | None     # first | step | None
    greedy: bool
    sample: int
    parent: str | None
    branch_turn: int | None   # first turn generated by this conversation (earlier turns copied from parent)
    first_user: str

    def to_dict(self) -> dict:
        return asdict(self)


def first_user(goal: str, sentence: str | None, cue: str | None) -> str:
    return " ".join(x for x in (goal + " Help me make a plan.", sentence, cue) if x)


def build_specs(cfg: dict, scenarios: list[str] | None = None) -> list[ConvSpec]:
    mt = cfg["multiturn"]
    levels = {h["canonical"]: h for h in cfg["horizons"]}
    items = {i["id"]: i for i in cfg["choice"]["implicit"]}
    scen = scenarios or list(SCENARIOS)
    branch = mt["cue_step"] + 1                    # turn k asks for step k-1
    specs: list[ConvSpec] = []

    def add(cid, sc, cond, var, level, h_text, cue=None, where=None, greedy=True, sample=0, parent=None, sentence=None):
        # true horizon in years: the canonical level (base/unit) or the implicit item's twin (implicit/twin)
        y = parse_years(items[level]["twin"] if cond in ("implicit", "twin") else level) if level else math.nan
        cue_text = mt["cues"][cue] if (cue and where == "first") else None
        specs.append(ConvSpec(cid, sc, cond, var, level, h_text, y, cue, where, greedy, sample, parent,
                              branch if where == "step" else None, first_user(SCENARIOS[sc], sentence, cue_text)))

    def with_cues(cid, sc, cond, var, level, h_text, sentence, greedy=True, sample=0):
        add(cid, sc, cond, var, level, h_text, greedy=greedy, sample=sample, sentence=sentence)
        for c in mt["first_turn_cues"]:
            add(f"{cid}__first_{c}", sc, cond, var, level, h_text, c, "first", greedy, sample, None, sentence)
        for c in mt["later_cues"]:
            add(f"{cid}__step_{c}", sc, cond, var, level, h_text, c, "step", greedy, sample, cid, sentence)

    for sc, lv in itertools.product(scen, mt["horizons"]):
        with_cues(f"{sc}__base__{lv.replace(' ', '')}", sc, "base", "canonical", lv, lv,
                  mt["horizon_sentence"].format(h=lv))
        for form in mt["unit_forms"]:
            h = levels[lv]["forms"].get(form)
            if h:
                add(f"{sc}__{form}__{lv.replace(' ', '')}", sc, "unit", form, lv, h,
                    sentence=mt["horizon_sentence"].format(h=h))
    for sc, iid in itertools.product([s for s in mt["implicit_scenarios"] if s in scen], mt["implicit_items"]):
        it = items[iid]
        add(f"{sc}__implicit__{iid}", sc, "implicit", f"implicit:{iid}", iid, it["when"],
            sentence=mt["implicit_sentence"].format(when=it["when"]))
        add(f"{sc}__twin__{iid}", sc, "twin", f"twin:{iid}", iid, it["twin"],
            sentence=mt["horizon_sentence"].format(h=it["twin"]))
    for sc, s in itertools.product(scen, range(mt["free_form_samples"])):
        with_cues(f"{sc}__free__s{s}", sc, "free", "none", None, None, None, greedy=False, sample=s)
    ids = [s.conv_id for s in specs]
    assert len(ids) == len(set(ids)), "duplicate conversation ids"
    return specs


def user_message(spec: ConvSpec, cfg: dict, k: int) -> str:
    """User message that opens turn k (k = 1 first turn, k >= 2 Continue)."""
    if k == 1:
        return spec.first_user
    if spec.cue_where == "step" and k == spec.branch_turn:
        return f"{CONTINUE}. {cfg['multiturn']['cues'][spec.cue]}"
    return CONTINUE


def messages(spec: ConvSpec, cfg: dict, replies: list[str]) -> list[dict]:
    msgs = [{"role": "system", "content": SYSTEM}, {"role": "user", "content": user_message(spec, cfg, 1)}]
    for j, r in enumerate(replies, start=2):
        msgs += [{"role": "assistant", "content": r}, {"role": "user", "content": user_message(spec, cfg, j)}]
    return msgs


def run(specs: list[ConvSpec], cfg: dict, out_dir: Path, tok, model, layers: list[int], batch: int = 16,
        shard_size: int = 256, log=print) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    tok.padding_side = "left"
    cap = Capture(model, layers)
    by_id = {s.conv_id: s for s in specs}
    replies: dict[str, list[str]] = {s.conv_id: [] for s in specs}
    rows, acts, masks, shard, t0 = [], [], [], 0, time.time()

    def flush():
        nonlocal acts, masks, shard
        if acts:
            save_file({"acts": torch.stack(acts), "valid": torch.tensor(np.array(masks))},
                      str(out_dir / f"mt_acts_{shard:04d}.safetensors"))
            shard, acts, masks = shard + 1, [], []

    for k in range(1, N_TURNS + 1):
        for greedy in (True, False):
            group = [s for s in specs if s.greedy == greedy and (s.branch_turn is None or k >= s.branch_turn)]
            for b in range(0, len(group), batch):
                chunk = group[b:b + batch]
                prompts = [encode_prompt(tok, messages(s, cfg, replies[s.conv_id])) for s in chunk]
                pre = tok.encode(step_prefill(k - 1), add_special_tokens=False) if turn_kind(k) == "step" else []
                gen = generate_batch(tok, model, [p + pre for p in prompts], MAX_NEW[k], greedy, seed=1000 * k + b)
                for s, p, r in zip(chunk, prompts, gen):
                    r = pre + r
                    r, cut = cut_step_reply(tok, r) if turn_kind(k) == "step" else (r, False)
                    pos = turn_positions(tok, p, r)
                    acts.append(cap(model, p + r, [pos[n] if pos[n] is not None else 0 for n in POSITIONS]))
                    masks.append([pos[n] is not None for n in POSITIONS])
                    text = clean_reply(tok.decode(r))
                    replies[s.conv_id].append(text)
                    step = parse_step(text) if turn_kind(k) == "step" else {}
                    rows.append({**{x: y for x, y in s.to_dict().items() if x != "first_user"}, "turn": k,
                                 "kind": turn_kind(k), "copied": False, "shard": shard, "row_in_shard": len(acts) - 1,
                                 "user_msg": user_message(s, cfg, k)[:200], "prompt_len": len(p), "n_reply": len(r),
                                 "truncated": pos["E"] is None, "cut": cut, "reply": text,
                                 "outline_mentions_time": outline_mentions_time(text) if k == 1 else None,
                                 "step_no": step.get("step_no"), "h_step_text": step.get("h_step_text"),
                                 "h_step_years": step.get("h_step_years"), "positions": json.dumps(pos)})
                    if len(acts) == shard_size:
                        flush()
                log(f"turn {k} {'greedy' if greedy else 'sampled'} {b + len(chunk)}/{len(group)}  {time.time() - t0:.0f}s")
        # branched conversations copy their parent's reply for turns before the branch
        for s in specs:
            if s.branch_turn is not None and k < s.branch_turn:
                replies[s.conv_id].append(replies[s.parent][k - 1])
                prow = next(r for r in rows if r["conv_id"] == s.parent and r["turn"] == k)
                rows.append({**prow, **{x: y for x, y in s.to_dict().items() if x != "first_user"}, "copied": True})
    flush()
    df = pd.DataFrame(rows)
    df.to_parquet(out_dir / "multiturn.parquet")
    pd.DataFrame([s.to_dict() for s in specs]).to_parquet(out_dir / "conversations.parquet")
    log(f"multiturn done: {len(specs)} conversations, {int((~df.copied).sum())} generated turns, {shard} shards, "
        f"{time.time() - t0:.0f}s")
    assert all(len(replies[s]) == N_TURNS for s in by_id)
